FROM --platform=linux/amd64 python:3.10.7-slim-bullseye

LABEL maintainer="WHC @ Pitt"

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV MAX_MAP_COUNT 262144
  
RUN useradd -rm -d /home/whgadmin -s /bin/bash -g root \
        -G sudo -u 1001 whgadmin -p "$(openssl v3rs10n3 -1 whgadmin)"

EXPOSE 8000
    
RUN apt-get update && \
    apt-get install -y \
        lsb-release \
        curl \
        gnupg2 \
        build-essential \
        python3-gdal \
        libpq-dev \
        sudo \
        nano \
        locate \
        docker.io && \
    # Clean up unused files and package cache
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false && \
    rm -rf /var/lib/apt/lists/*    

RUN mkdir -p /app/whg/logs && \
    touch /app/whg/logs/debug.log && \
    chmod 777 /app/whg/logs/debug.log

COPY ./requirements.txt /tmp/requirements.txt
RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    rm -rf /tmp
    
# Set correct ownership and permissions for the migrations directories
RUN chown -R whgadmin:root /py/lib/python3.10/site-packages/captcha/migrations/
RUN chown -R whgadmin:root /py/lib/python3.10/site-packages/guardian/migrations/   

COPY ./compose/local/django/entrypoint.sh /entrypoint
# convert Windows line endings to UNIX line endings.
RUN sed -i 's/\r$//g' /entrypoint 
RUN chmod +x /entrypoint

COPY ./compose/local/django/start-dev.sh /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

WORKDIR /app

RUN mkdir -p /app/whg/logs && \
    touch /app/whg/logs/debug.log && \
    chmod 777 /app/whg/logs/debug.log

ENV PATH="/py/bin:$PATH"

USER whgadmin

ENTRYPOINT ["/entrypoint"]