# Generated by Django 4.1.7 on 2024-10-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toponym', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('is_romanised', models.BooleanField(default=False)),
                ('phonetic_embedding', models.JSONField(blank=True, null=True)),
                ('semantic_embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('toponym', 'language', 'is_romanised')},
            },
        ),
        migrations.CreateModel(
            name='NPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255, null=True)),
                ('primary_name', models.CharField(max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geometry_bbox', models.JSONField(blank=True, null=True)),
                ('feature_classes', models.JSONField(blank=True, null=True)),
                ('ccodes', models.JSONField(blank=True, null=True)),
                ('lpf_feature', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('npr_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_toponym_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('npr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='ingestion.npr')),
                ('toponym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='ingestion.toponym')),
            ],
        ),
        migrations.CreateModel(
            name='ToponymLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_toponym_id', models.CharField(blank=True, max_length=255, null=True)),
                ('toponym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='ingestion.toponym')),
            ],
            options={
                'unique_together': {('toponym', 'source_toponym_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='attestation',
            constraint=models.UniqueConstraint(fields=('npr', 'toponym', 'start', 'end'), name='unique_npr_toponym_time'),
        ),
        migrations.AddConstraint(
            model_name='attestation',
            constraint=models.UniqueConstraint(fields=('npr', 'source_toponym_id', 'start', 'end'), name='unique_npr_source_toponym'),
        ),
    ]
