# Generated by Django 4.1.7 on 2024-10-09 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('item_path', models.CharField(max_length=255)),
                ('api_item', models.CharField(blank=True, max_length=255, null=True)),
                ('update_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toponym', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('is_romanised', models.BooleanField(default=False)),
                ('phonetic_embedding', models.JSONField(blank=True, null=True)),
                ('semantic_embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('toponym', 'language', 'is_romanised')},
            },
        ),
        migrations.CreateModel(
            name='NPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, null=True)),
                ('primary_name', models.CharField(max_length=255, null=True)),
                ('geometry_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geometry_bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('feature_classes', models.JSONField()),
                ('lpf_feature', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nprs', to='ingestion.datasetconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('npr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='ingestion.npr')),
                ('toponym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='ingestion.toponym')),
            ],
            options={
                'unique_together': {('npr', 'toponym', 'start', 'end')},
            },
        ),
    ]
