# Generated by Django 4.1.7 on 2023-07-23 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placegeom_s2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placegeom',
            name='s2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=20), blank=True, null=True, size=None),
        ),
    ]
