# Generated by Django 4.1.7 on 2023-08-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_closematch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseMatch',
        ),
    ]
