# Generated by Django 4.1.7 on 2023-08-03 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_delete_closematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis', models.CharField(blank=True, choices=[('authid', 'authority id'), ('reviewed', 'reviewed'), ('imported', 'imported')], max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matcher', to=settings.AUTH_USER_MODEL)),
                ('place1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_match1', to='places.place')),
                ('place2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_match2', to='places.place')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='django_celery_results.taskresult')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
