# Generated by Django 4.1.7 on 2023-08-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_closematch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closematch',
            old_name='place1',
            new_name='place_a',
        ),
        migrations.RenameField(
            model_name='closematch',
            old_name='place2',
            new_name='place_b',
        ),
    ]
