# Generated by Django 4.1.7 on 2023-09-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_place1_closematch_place_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placegeom',
            name='s2',
        ),
    ]
