# Generated by Django 4.1.7 on 2023-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_place1_closematch_place_a_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='place',
        #     name='attestation_year',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='place',
            name='idx_pub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='closematch',
            table='close_matches',
        ),
    ]
