# Generated by Django 4.1.7 on 2023-11-26 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_attestation_year_place_idx_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placegeom',
            name='s2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None),
        ),
    ]
