# Generated by Django 4.1.7 on 2023-11-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_placegeom_s2'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='idx_builder',
            field=models.BooleanField(default=False),
        ),
    ]
