# Generated by Django 4.1.7 on 2024-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_placegeom_reviewer_placelink_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placegeom',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='placelink',
            old_name='created',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='place',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placename',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
