# Generated by Django 4.1.7 on 2024-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_placename_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='attestation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
