# Generated by Django 4.1.7 on 2024-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_place_attestation_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placename',
            unique_together={('place', 'src_id', 'jsonb')},
        ),
    ]
