# Generated by Django 4.1.7 on 2024-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_placename_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placelink',
            unique_together={('place', 'src_id', 'jsonb')},
        ),
    ]
