# Generated by Django 4.1.7 on 2024-05-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_placewhen_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placetype',
            unique_together={('place', 'src_id', 'jsonb')},
        ),
    ]
