# Generated by Django 4.1.7 on 2024-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_placerelated_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placelink',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='placename',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='placerelated',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='placetype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='placewhen',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='placedescription',
            index=models.Index(fields=['place'], name='place_descr_place_i_ae86be_idx'),
        ),
    ]
