# Generated by Django 4.1.7 on 2024-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='web_page',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
