# Generated by Django 4.1.7 on 2024-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_must_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='given_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
