# Generated by Django 4.1.7 on 2024-07-25 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='Invalid ORCiD. Format should be: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')]),
        ),
    ]
