# Generated by Django 4.1.7 on 2024-05-23 08:04

from django.db import migrations
from users.models import User, Person

def copy_user_data_to_person(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Person = apps.get_model('users', 'Person')

    # Copy data from User to Person
    for user in User.objects.all():
        person = Person.objects.create(
            given_name=user.given_name,
            family_name=user.surname,
            affiliation=user.affiliation,
        )
        user.person = person
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_person'),
    ]

    operations = [
        migrations.RunPython(copy_user_data_to_person),
    ]
