# Generated by Django 4.1.7 on 2023-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('ccodes', 'Country codes'), ('copied', 'CopyPasted GeoJSON'), ('search', 'Region/Polity record'), ('drawn', 'User drawn'), ('predefined', 'World Regions')], max_length=20),
        ),
    ]
