# Generated by Django 4.1.7 on 2023-09-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_alter_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('predefined', 'World Regions'), ('drawn', 'User drawn'), ('search', 'Region/Polity record'), ('copied', 'CopyPasted GeoJSON'), ('ccodes', 'Country codes')], max_length=20),
        ),
    ]
