# Generated by Django 4.1.7 on 2023-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_alter_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=(
                ('ccodes', 'Country codes'), ('drawn', 'User drawn'),
                ('predefined', 'World Regions'), ('copied', 'CopyPasted GeoJSON'),
                ('search', 'Region/Polity record')), max_length=20),
        ),
    ]
