# Generated by Django 4.1.7 on 2025-09-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.CharField(blank=True, max_length=7, primary_key=True, serialize=False)),
                ('source', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=9)),
                ('editorialNote', models.TextField(blank=True)),
                ('sameAs', models.URLField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Authorities',
                'db_table': 'periods_authority',
            },
        ),
        migrations.CreateModel(
            name='Chrononym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('languageTag', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Chrononyms',
                'db_table': 'periods_chrononym',
                'unique_together': {('label', 'languageTag')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=6)),
                ('language', models.URLField(blank=True, max_length=1024)),
                ('chrononym', models.CharField(blank=True, max_length=91)),
                ('editorialNote', models.TextField(blank=True)),
                ('spatialCoverageDescription', models.CharField(blank=True, max_length=183)),
                ('languageTag', models.CharField(blank=True, max_length=7)),
                ('sameAs', models.URLField(blank=True, max_length=1024)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('note', models.TextField(blank=True)),
                ('broader', models.CharField(blank=True, max_length=11)),
                ('source', models.JSONField(blank=True, null=True)),
                ('narrower', models.JSONField(blank=True, null=True)),
                ('script', models.URLField(blank=True, max_length=1024)),
                ('derivedFrom', models.JSONField(blank=True, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='periods.authority')),
                ('chrononyms', models.ManyToManyField(related_name='periods', to='periods.chrononym')),
            ],
            options={
                'verbose_name_plural': 'Periods',
                'db_table': 'periods_period',
            },
        ),
        migrations.CreateModel(
            name='SpatialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=1024, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Spatial Entities',
                'db_table': 'periods_spatialentity',
            },
        ),
        migrations.CreateModel(
            name='TemporalBound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], max_length=5)),
                ('year', models.JSONField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=91)),
                ('latestYear', models.BigIntegerField(blank=True, null=True)),
                ('earliestYear', models.BigIntegerField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounds', to='periods.period')),
            ],
            options={
                'verbose_name_plural': 'Temporal Bounds',
                'db_table': 'periods_temporalbound',
            },
        ),
        migrations.AddField(
            model_name='period',
            name='spatialCoverage',
            field=models.ManyToManyField(related_name='periods', to='periods.spatialentity'),
        ),
    ]
