# Generated by Django 4.1.7 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrononym',
            name='languageTag',
            field=models.CharField(max_length=20),
        ),
    ]
