# Generated by Django 4.1.7 on 2025-09-27 09:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_alter_chrononym_languagetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazetteerTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('commit_hash', models.CharField(max_length=40)),
                ('last_processed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periods_gazetteer_tracker',
            },
        ),
        migrations.AddField(
            model_name='spatialentity',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='spatialentity',
            name='gazetteer_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='spatialentity',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
