# Generated by Django 4.1.7 on 2025-09-27 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_gazetteertracker_spatialentity_bbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
