# Generated by Django 4.1.7 on 2025-09-27 13:12
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0004_period_bbox'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
    ]
