# Generated by Django 4.1.7 on 2023-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_remove_collection_submitted_alter_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlink',
            name='link_type',
            field=models.CharField(choices=[('webpage', '<i class="fas fa-window-maximize"></i>'), ('image', '<img src="/static/images/noun-photo.svg" width="16"/>'), ('document', '<i class="far fa-file-pdf linky"></i>')], default='webpage', max_length=10),
        ),
    ]
