# Generated by Django 4.1.7 on 2023-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_alter_collectionlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='visParameters',
            field=models.JSONField(default=dict),
        ),
    ]
