# Generated by Django 4.1.7 on 2023-12-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_collection_visparameters'),
        ('collection', '0021_remove_collection_new_datasets_collection_datasets_and_more'),
    ]

    operations = [
    ]
