# Generated by Django 4.1.7 on 2023-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_merge_20231222_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='visParameters',
        ),
        migrations.AddField(
            model_name='collection',
            name='vis_parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
