# Generated by Django 4.1.7 on 2024-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_collectiongroup_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiongroupuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('owner', 'Owner'), ('member', 'Member')], max_length=20),
        ),
    ]
