# Generated by Django 4.1.7 on 2024-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_alter_collectiongroupuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='build_type',
            field=models.CharField(choices=[('discrete', 'Discrete datasets'), ('conflated', 'Conflated datasets')], default='discrete', max_length=10),
        ),
    ]
