# Generated by Django 4.1.7 on 2024-04-18 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0029_rename_created_collection_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='collection',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collabs', to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_collab', to=settings.AUTH_USER_MODEL),
        ),
    ]
