# Generated by Django 4.1.7 on 2024-04-29 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_alter_collectionuser_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rel_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None),
        ),
    ]
