# Generated by Django 4.1.7 on 2024-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0031_alter_collection_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collplace',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
