# Generated by Django 4.1.7 on 2024-05-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0035_alter_colldataset_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='build_type',
        ),
    ]
