# Generated by Django 4.1.7 on 2024-05-23 18:58

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_remove_collection_build_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='coordinate_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='vis_parameters',
            field=models.JSONField(blank=True, default=collection.models.default_vis_parameters, null=True),
        ),
    ]
