# Generated by Django 4.1.7 on 2026-09-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Shown in full at the point of contribution.')),
                ('licence_spdx', models.CharField(default='MIT', help_text="Must be compatible with Epitran's own rules, which are MIT.", max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('signed_off', models.BooleanField(default=False)),
                ('signed_off_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'contribution terms',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Epitran mode code, e.g. 'mya-Mymr'.", max_length=32, unique=True)),
                ('language_code', models.CharField(db_index=True, help_text='ISO 639-3.', max_length=8)),
                ('script_code', models.CharField(db_index=True, help_text='ISO 15924.', max_length=8)),
                ('language_name', models.CharField(blank=True, max_length=128)),
                ('script_name', models.CharField(blank=True, max_length=128)),
                ('posture', models.CharField(choices=[('proposed', 'Proposed — drafted by WHG, not installed, awaiting judgement'), ('shipped', 'In production — presumed adequate until someone says otherwise')], default='shipped', max_length=16)),
                ('source_repo', models.CharField(blank=True, max_length=128)),
                ('source_ref', models.CharField(blank=True, max_length=128)),
                ('source_path', models.CharField(blank=True, max_length=512)),
                ('corpus_name_count', models.PositiveIntegerField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('present_upstream', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RuleSetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_sha', models.CharField(db_index=True, max_length=64)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='phonetics.ruleset')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'unique_together': {('ruleset', 'blob_sha')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orth', models.CharField(help_text='Grapheme, NFD-normalised.', max_length=64)),
                ('orth_source', models.CharField(blank=True, help_text='Grapheme exactly as written in the file.', max_length=64)),
                ('current_ipa', models.CharField(blank=True, help_text='NFD-normalised.', max_length=64)),
                ('current_ipa_source', models.CharField(blank=True, max_length=64)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('present_upstream', models.BooleanField(default=True)),
                ('corpus_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('lint_codes', models.JSONField(blank=True, default=list)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('accept_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('unsure_count', models.PositiveIntegerField(default=0)),
                ('distinct_proposal_count', models.PositiveIntegerField(default=0)),
                ('stale_review_count', models.PositiveIntegerField(default=0)),
                ('first_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_first_seen', to='phonetics.rulesetversion')),
                ('last_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_last_seen', to='phonetics.rulesetversion')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='phonetics.ruleset')),
            ],
            options={
                'ordering': ['ruleset', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=8)),
                ('script_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('level', models.CharField(choices=[('native', 'Native speaker'), ('fluent', 'Fluent'), ('academic', 'Academic/professional knowledge of the language'), ('working', 'Working knowledge'), ('script_only', 'I read the script but do not speak the language')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_competences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['language_code', 'script_code'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('credit_name', models.CharField(blank=True, help_text='Name to credit, if the reviewer wants crediting.', max_length=200)),
                ('credit_public', models.BooleanField(default=True)),
                ('orcid', models.CharField(blank=True, max_length=32)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='phonetics.contributionterms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('accept', 'The current value is right'), ('correct', 'The current value is wrong — here is a better one'), ('unsure', 'I am not sure — flag for someone else')], max_length=16)),
                ('proposed_ipa', models.CharField(blank=True, help_text='NFD-normalised; only for a CORRECT verdict.', max_length=64)),
                ('reviewed_ipa', models.CharField(blank=True, help_text='rule.current_ipa as it stood when reviewed.', max_length=64)),
                ('confidence', models.CharField(choices=[('high', 'Confident'), ('medium', 'Fairly confident'), ('low', 'Tentative')], default='medium', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('competence_level', models.CharField(blank=True, max_length=16)),
                ('panphon_version', models.CharField(blank=True, max_length=32)),
                ('ipa_all_sha256', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('adopted_upstream_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='phonetics.revieweragreement')),
                ('reviewed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='phonetics.rulesetversion')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_reviews', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='phonetics.rule')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PolicyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(help_text='The question, and what turns on the answer.')),
                ('options', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_option', models.CharField(blank=True, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phonetic_questions', to=settings.AUTH_USER_MODEL)),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_questions', to='phonetics.ruleset')),
            ],
            options={
                'ordering': ['status', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('competence_level', models.CharField(blank=True, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_answers', to='phonetics.revieweragreement')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='phonetics.policyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_policy_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['ruleset', 'review_count'], name='phonetics_r_ruleset_2f5534_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['corpus_frequency'], name='phonetics_r_corpus__24b3a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('ruleset', 'orth')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewercompetence',
            unique_together={('user', 'language_code', 'script_code')},
        ),
        migrations.AlterUniqueTogether(
            name='revieweragreement',
            unique_together={('user', 'terms')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rule', 'is_latest'], name='phonetics_r_rule_id_b6e439_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created'], name='phonetics_r_reviewe_ac1b95_idx'),
        ),
    ]
