# Generated by Django 4.1.7 on 2026-09-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phonetics', '0004_cc_by_terms_and_q13'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRuleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orth', models.CharField(help_text='Grapheme, NFD-normalised.', max_length=64)),
                ('orth_source', models.CharField(blank=True, max_length=64)),
                ('proposed_ipa', models.CharField(blank=True, help_text='NFD-normalised; blank means "produces nothing".', max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('high', 'Confident'), ('medium', 'Fairly confident'), ('low', 'Tentative')], default='medium', max_length=16)),
                ('competence_level', models.CharField(blank=True, max_length=16)),
                ('example_name', models.CharField(blank=True, max_length=200)),
                ('panphon_version', models.CharField(blank=True, max_length=32)),
                ('ipa_all_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('declined', 'Declined')], default='open', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('adopted_upstream_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_rule_proposals', to='phonetics.revieweragreement')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_new_rules', to=settings.AUTH_USER_MODEL)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_rule_proposals', to='phonetics.ruleset')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='newruleproposal',
            index=models.Index(fields=['ruleset', 'orth'], name='phonetics_n_ruleset_085da3_idx'),
        ),
    ]
