# Generated by Django 4.1.7 on 2026-09-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_seed_authority_licences'),
        ('phonetics', '0006_narrow_myanmar_register_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionterms',
            name='upstream_licence',
            field=models.ForeignKey(blank=True, help_text='The vocabulary row for upstream_licence_spdx.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phonetic_upstream_terms', to='licensing.license'),
        ),
        migrations.AddField(
            model_name='contributionterms',
            name='upstream_licence_spdx',
            field=models.CharField(blank=True, help_text='SPDX id of the licence rows are contributed upstream under. Blank if WHG does not contribute upstream under these terms.', max_length=64),
        ),
        migrations.AlterField(
            model_name='contributionterms',
            name='licence_spdx',
            field=models.CharField(default='CC-BY-4.0', help_text='SPDX id of the licence WHG publishes the citable dataset under.', max_length=64),
        ),
    ]
