# Replace default postgres startup script
FROM postgis/postgis:15-3.4
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./start-postgres.sh /docker-entrypoint-initdb.d/10_postgis.sh
RUN sed -i 's/\r$//g' /docker-entrypoint-initdb.d/10_postgis.sh
RUN chmod +x /docker-entrypoint-initdb.d/10_postgis.sh
