# Generated by Django 4.1.7 on 2023-09-02 17:38

import django.contrib.postgres.fields
from django.db import migrations, models
import traces.models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0004_alter_traceannotation_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceannotation',
            name='relation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=traces.models.getDefaultRelations, null=True, size=None),
        ),
    ]
