# Generated by Django 4.1.7 on 2024-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0005_alter_traceannotation_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceannotation',
            name='include_matches',
            field=models.BooleanField(default=True),
        ),
    ]
