# Generated by Django 4.1.7 on 2024-05-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0006_traceannotation_include_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceannotation',
            name='include_matches',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='motivation',
            field=models.CharField(default='locating', max_length=20, null=True),
        ),
    ]
