# Generated by Django 4.1.7 on 2024-05-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0007_alter_traceannotation_include_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceannotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
