# Generated by Django 4.1.7 on 2024-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0008_alter_traceannotation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceannotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-28'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traceannotation',
            name='include_matches',
            field=models.BooleanField(default=True),
        ),
    ]
