# Generated by Django 4.1.7 on 2025-09-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.TextField()),
                ('user_type', models.CharField(choices=[('authenticated', 'Authenticated'), ('anonymous', 'Anonymous')], max_length=20)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='requestcount',
            index=models.Index(fields=['date', 'url', 'user_type'], name='metrics_req_date_d1deec_idx'),
        ),
    ]
