# Generated by Django 4.1.7 on 2025-09-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='metrics.requestcount')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyvisitor',
            index=models.Index(fields=['visitor_hash'], name='metrics_dai_visitor_2a24b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyvisitor',
            unique_together={('request_count', 'visitor_hash')},
        ),
    ]
