# Generated by Django 4.1.7 on 2025-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_dailyvisitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcount',
            name='new',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestcount',
            name='unique',
            field=models.BigIntegerField(default=0),
        ),
    ]
