# Generated by Django 4.1.7 on 2025-09-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_requestcount_new_requestcount_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcount',
            name='new',
        ),
        migrations.RemoveField(
            model_name='requestcount',
            name='unique',
        ),
    ]
