# Generated by Django 4.1.7 on 2025-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_remove_requestcount_new_remove_requestcount_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitor',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
