# Generated by Django 4.1.7 on 2025-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_dailyvisitor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
