# Generated by Django 4.1.7 on 2023-12-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_remove_collection_visparameters_and_more'),
        ('main', '0005_alter_link_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='collection.collection'),
        ),
    ]
