# Generated by Django 4.1.7 on 2024-01-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_collection_build_type'),
        ('datasets', '0009_alter_dataset_image_file_alter_datasetuser_role'),
        ('main', '0006_log_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiletype', models.CharField(blank=True, choices=[('normal', 'Normal'), ('heatmap', 'Heatmap')], max_length=20, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to='collection.collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to='datasets.dataset')),
            ],
        ),
    ]
