# Generated by Django 4.1.7 on 2024-02-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_announcement_headline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcements',
        ),
    ]
