# Generated by Django 4.1.7 on 2024-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_downloadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
