# Generated by Django 4.1.7 on 2024-08-22 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('given', models.CharField(blank=True, max_length=255, null=True)),
                ('dropping_particle', models.CharField(blank=True, max_length=255, null=True)),
                ('non_dropping_particle', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('comma_suffix', models.BooleanField(default=False)),
                ('static_ordering', models.BooleanField(default=False)),
                ('literal', models.CharField(blank=True, max_length=255, null=True)),
                ('parse_names', models.BooleanField(default=False)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid ORCiD. Format should be: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
