# Generated by Django 4.1.7 on 2024-09-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueToponym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ccodes', models.JSONField(default=list)),
                ('timespans', models.JSONField(default=list)),
                ('instance_count', models.IntegerField(default=1)),
            ],
        ),
    ]
