# Generated by Django 4.1.7 on 2024-09-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uniquetoponym',
            table='toponyms',
        ),
    ]
