# Generated by Django 4.1.7 on 2024-09-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_alter_uniquetoponym_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueToponym',
            new_name='Toponym',
        ),
    ]
