# Generated by Django 4.1.7 on 2024-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0004_rename_timespans_toponym_yearspans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toponym',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
