# Generated by Django 4.1.7 on 2024-09-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0005_alter_toponym_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toponym',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
