# Generated by Django 4.1.7 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0006_alter_toponym_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toponym',
            name='ccodes',
            field=models.JSONField(db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name='toponym',
            name='instance_count',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='toponym',
            name='yearspans',
            field=models.JSONField(db_index=True, default=list),
        ),
    ]
