--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: areas; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.areas (
    id bigint NOT NULL,
    type character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(2044) NOT NULL,
    ccodes character varying(2)[],
    geojson jsonb,
    created timestamp with time zone NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.areas OWNER TO karlg;

--
-- Name: areas_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.areas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO karlg;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO karlg;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO karlg;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO karlg;

--
-- Name: captcha_captchastore; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.captcha_captchastore (
    id bigint NOT NULL,
    challenge character varying(32) NOT NULL,
    response character varying(32) NOT NULL,
    hashkey character varying(40) NOT NULL,
    expiration timestamp with time zone NOT NULL
);


ALTER TABLE public.captcha_captchastore OWNER TO karlg;

--
-- Name: captcha_captchastore_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.captcha_captchastore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.captcha_captchastore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_collplace; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_collplace (
    id bigint NOT NULL,
    sequence integer NOT NULL,
    collection_id bigint NOT NULL,
    place_id bigint NOT NULL
);


ALTER TABLE public.collection_collplace OWNER TO karlg;

--
-- Name: collection_collplace_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_collplace ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_collplace_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_group; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_group (
    id bigint NOT NULL,
    title character varying(300) NOT NULL,
    description text,
    keywords character varying(50)[],
    created timestamp with time zone NOT NULL,
    start_date timestamp with time zone,
    due_date timestamp with time zone,
    owner_id bigint NOT NULL,
    gallery boolean NOT NULL,
    gallery_required boolean NOT NULL,
    type character varying(8) NOT NULL,
    file character varying(100)
);


ALTER TABLE public.collection_group OWNER TO karlg;

--
-- Name: collection_group_collections; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_group_collections (
    id bigint NOT NULL,
    collectiongroup_id bigint NOT NULL,
    collection_id bigint NOT NULL
);


ALTER TABLE public.collection_group_collections OWNER TO karlg;

--
-- Name: collection_group_collections_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_group_collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_group_collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_group_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_group_user; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_group_user (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    collectiongroup_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.collection_group_user OWNER TO karlg;

--
-- Name: collection_group_user_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_group_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_group_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_link; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_link (
    id bigint NOT NULL,
    label character varying(200),
    uri text NOT NULL,
    link_type character varying(10) NOT NULL,
    license character varying(64),
    collection_id bigint NOT NULL
);


ALTER TABLE public.collection_link OWNER TO karlg;

--
-- Name: collection_link_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_user; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collection_user (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    collection_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.collection_user OWNER TO karlg;

--
-- Name: collection_user_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collection_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collection_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collections; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collections (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    keywords character varying(50)[],
    rel_keywords character varying(30)[],
    creator character varying(500),
    contact character varying(500),
    webpage character varying(200),
    collection_class character varying(12) NOT NULL,
    image_file character varying(100),
    file character varying(100),
    created timestamp with time zone,
    status character varying(12),
    featured integer,
    public boolean,
    nominated boolean,
    owner_id bigint NOT NULL,
    "group" bigint,
    nominate_date timestamp with time zone,
    submit_date timestamp with time zone
);


ALTER TABLE public.collections OWNER TO karlg;

--
-- Name: collections_datasets; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.collections_datasets (
    id bigint NOT NULL,
    collection_id bigint NOT NULL,
    dataset_id bigint NOT NULL
);


ALTER TABLE public.collections_datasets OWNER TO karlg;

--
-- Name: collections_datasets_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collections_datasets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_datasets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    tag character varying(20) NOT NULL,
    note character varying(2044),
    created timestamp with time zone,
    place_id_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.comments OWNER TO karlg;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.countries (
    id bigint NOT NULL,
    tgnid integer,
    tgnlabel character varying(255),
    iso character varying(2) NOT NULL,
    gnlabel character varying(255) NOT NULL,
    geonameid integer NOT NULL,
    un character varying(3),
    variants character varying(512),
    mpoly public.geometry(MultiPolygon,4326) NOT NULL
);


ALTER TABLE public.countries OWNER TO karlg;

--
-- Name: countries_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dataset_file; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.dataset_file (
    id bigint NOT NULL,
    rev integer,
    file character varying(100) NOT NULL,
    format character varying(12) NOT NULL,
    datatype character varying(12) NOT NULL,
    delimiter character varying(5),
    df_status character varying(12),
    upload_date timestamp with time zone,
    header character varying(30)[],
    numrows integer,
    dataset_id_id bigint NOT NULL
);


ALTER TABLE public.dataset_file OWNER TO karlg;

--
-- Name: dataset_file_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.dataset_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dataset_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dataset_user; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.dataset_user (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    dataset_id_id bigint NOT NULL,
    user_id_id bigint NOT NULL
);


ALTER TABLE public.dataset_user OWNER TO karlg;

--
-- Name: dataset_user_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.dataset_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dataset_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: datasets; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.datasets (
    id bigint NOT NULL,
    label character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(2044) NOT NULL,
    webpage character varying(200),
    create_date timestamp with time zone,
    uri_base character varying(200),
    image_file character varying(100),
    featured integer,
    bbox public.geometry(Polygon,4326),
    core boolean NOT NULL,
    public boolean NOT NULL,
    ds_status character varying(12),
    creator character varying(500),
    source character varying(500),
    contributors character varying(500),
    citation character varying(2044),
    datatype character varying(12) NOT NULL,
    numrows integer,
    numlinked integer,
    total_links integer,
    owner_id bigint NOT NULL
);


ALTER TABLE public.datasets OWNER TO karlg;

--
-- Name: datasets_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.datasets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datasets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO karlg;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_chordcounter; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_celery_results_chordcounter (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    sub_tasks text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_count_check CHECK ((count >= 0))
);


ALTER TABLE public.django_celery_results_chordcounter OWNER TO karlg;

--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_chordcounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_groupresult; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_celery_results_groupresult (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text
);


ALTER TABLE public.django_celery_results_groupresult OWNER TO karlg;

--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_groupresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_taskresult; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_celery_results_taskresult (
    id integer NOT NULL,
    task_id character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text,
    date_done timestamp with time zone NOT NULL,
    traceback text,
    meta text,
    task_args text,
    task_kwargs text,
    task_name character varying(255),
    worker character varying(100),
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255)
);


ALTER TABLE public.django_celery_results_taskresult OWNER TO karlg;

--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_taskresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO karlg;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO karlg;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO karlg;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO karlg;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guardian_groupobjectpermission; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.guardian_groupobjectpermission (
    id bigint NOT NULL,
    object_pk character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.guardian_groupobjectpermission OWNER TO karlg;

--
-- Name: guardian_groupobjectpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.guardian_groupobjectpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardian_groupobjectpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guardian_userobjectpermission; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.guardian_userobjectpermission (
    id bigint NOT NULL,
    object_pk character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    permission_id integer NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.guardian_userobjectpermission OWNER TO karlg;

--
-- Name: guardian_userobjectpermission_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.guardian_userobjectpermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guardian_userobjectpermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hits; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.hits (
    id bigint NOT NULL,
    task_id character varying(50) NOT NULL,
    authority character varying(12) NOT NULL,
    query_pass character varying(12) NOT NULL,
    src_id character varying(2044) NOT NULL,
    score double precision NOT NULL,
    reviewed boolean NOT NULL,
    matched boolean NOT NULL,
    flag boolean NOT NULL,
    authrecord_id character varying(255) NOT NULL,
    json jsonb,
    geom jsonb,
    dataset_id bigint NOT NULL,
    place_id bigint NOT NULL
);


ALTER TABLE public.hits OWNER TO karlg;

--
-- Name: hits_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.hits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: links; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.links (
    id bigint NOT NULL,
    uri character varying(200) NOT NULL,
    label character varying(200),
    link_type character varying(10) NOT NULL,
    license character varying(64),
    collection_id bigint,
    collection_group_id bigint,
    place_id bigint,
    trace_annotation_id bigint
);


ALTER TABLE public.links OWNER TO karlg;

--
-- Name: links_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.log (
    id bigint NOT NULL,
    category character varying(20) NOT NULL,
    logtype character varying(20) NOT NULL,
    subtype character varying(50),
    note character varying(2044),
    "timestamp" timestamp with time zone,
    dataset_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.log OWNER TO karlg;

--
-- Name: log_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_depiction; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_depiction (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_depiction OWNER TO karlg;

--
-- Name: place_depiction_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_depiction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_depiction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_description; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_description (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    task_id character varying(100),
    place_id bigint NOT NULL
);


ALTER TABLE public.place_description OWNER TO karlg;

--
-- Name: place_description_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_description ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_description_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_geom; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_geom (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    task_id character varying(100),
    geom public.geometry(Geometry,4326),
    created timestamp with time zone,
    geom_src character varying(30),
    place_id bigint NOT NULL
);


ALTER TABLE public.place_geom OWNER TO karlg;

--
-- Name: place_geom_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_geom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_geom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_link; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_link (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    task_id character varying(100),
    review_note character varying(2044),
    black_parent integer,
    created timestamp with time zone,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_link OWNER TO karlg;

--
-- Name: place_link_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_name; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_name (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    task_id character varying(100),
    toponym character varying(2044) NOT NULL,
    name_src_id bigint,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_name OWNER TO karlg;

--
-- Name: place_name_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_name ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_name_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_related; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_related (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_related OWNER TO karlg;

--
-- Name: place_related_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_related ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_related_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_type; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_type (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    aat_id integer,
    fclass character varying(1) NOT NULL,
    place_id bigint NOT NULL
);


ALTER TABLE public.place_type OWNER TO karlg;

--
-- Name: place_type_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_when; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.place_when (
    id bigint NOT NULL,
    src_id character varying(100) NOT NULL,
    jsonb jsonb,
    minmax integer[],
    place_id bigint NOT NULL
);


ALTER TABLE public.place_when OWNER TO karlg;

--
-- Name: place_when_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.place_when ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_when_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: places; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.places (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    src_id character varying(2044) NOT NULL,
    ccodes character varying(2)[] NOT NULL,
    minmax integer[],
    timespans jsonb,
    fclasses character varying(1)[],
    indexed boolean NOT NULL,
    flag boolean NOT NULL,
    review_wd integer,
    review_tgn integer,
    review_whg integer,
    dataset character varying(20) NOT NULL
);


ALTER TABLE public.places OWNER TO karlg;

--
-- Name: places_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_file; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.resource_file (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    filetype character varying(12) NOT NULL,
    resource_id bigint NOT NULL
);


ALTER TABLE public.resource_file OWNER TO karlg;

--
-- Name: resource_file_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.resource_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_image; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.resource_image (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    resource_id bigint NOT NULL
);


ALTER TABLE public.resource_image OWNER TO karlg;

--
-- Name: resource_image_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.resource_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.resources (
    id bigint NOT NULL,
    create_date timestamp with time zone,
    pub_date timestamp with time zone NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(12) NOT NULL,
    description text NOT NULL,
    subjects character varying(2044) NOT NULL,
    gradelevels character varying(24)[] NOT NULL,
    keywords character varying(24)[] NOT NULL,
    authors character varying(500) NOT NULL,
    contact character varying(500),
    webpage character varying(200),
    public boolean NOT NULL,
    featured integer,
    regions character varying(24),
    status character varying(12),
    owner_id bigint NOT NULL
);


ALTER TABLE public.resources OWNER TO karlg;

--
-- Name: resources_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sources; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.sources (
    id bigint NOT NULL,
    src_id character varying(30) NOT NULL,
    uri character varying(200),
    label character varying(255) NOT NULL,
    citation character varying(500),
    owner_id bigint NOT NULL
);


ALTER TABLE public.sources OWNER TO karlg;

--
-- Name: sources_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trace_annotations; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.trace_annotations (
    id bigint NOT NULL,
    src_id character varying(2044),
    note character varying(2044),
    image_file character varying(100),
    relation character varying(30)[],
    start character varying(11),
    "end" character varying(11),
    sequence integer,
    anno_type character varying(20),
    motivation character varying(20) NOT NULL,
    created timestamp with time zone NOT NULL,
    saved boolean NOT NULL,
    "when" jsonb,
    collection bigint NOT NULL,
    owner_id bigint NOT NULL,
    place bigint NOT NULL,
    archived boolean NOT NULL
);


ALTER TABLE public.trace_annotations OWNER TO karlg;

--
-- Name: trace_annotations_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.trace_annotations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trace_annotations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trace_relations; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.trace_relations (
    id bigint NOT NULL,
    relation character varying(255) NOT NULL,
    collection bigint NOT NULL
);


ALTER TABLE public.trace_relations OWNER TO karlg;

--
-- Name: trace_relations_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.trace_relations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trace_relations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: types; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.types (
    id bigint NOT NULL,
    aat_id integer NOT NULL,
    parent_id integer,
    term character varying(100) NOT NULL,
    term_full character varying(100) NOT NULL,
    note text NOT NULL,
    fclass character varying(1)
);


ALTER TABLE public.types OWNER TO karlg;

--
-- Name: types_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    affiliation character varying(255),
    role character varying(24) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL
);


ALTER TABLE public.users_user OWNER TO karlg;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO karlg;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: karlg
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO karlg;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: karlg
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: areas areas_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: captcha_captchastore captcha_captchastore_hashkey_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.captcha_captchastore
    ADD CONSTRAINT captcha_captchastore_hashkey_key UNIQUE (hashkey);


--
-- Name: captcha_captchastore captcha_captchastore_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.captcha_captchastore
    ADD CONSTRAINT captcha_captchastore_pkey PRIMARY KEY (id);


--
-- Name: collection_collplace collection_collplace_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_collplace
    ADD CONSTRAINT collection_collplace_pkey PRIMARY KEY (id);


--
-- Name: collection_group_collections collection_group_collect_collectiongroup_id_colle_2315fcad_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_collections
    ADD CONSTRAINT collection_group_collect_collectiongroup_id_colle_2315fcad_uniq UNIQUE (collectiongroup_id, collection_id);


--
-- Name: collection_group_collections collection_group_collections_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_collections
    ADD CONSTRAINT collection_group_collections_pkey PRIMARY KEY (id);


--
-- Name: collection_group collection_group_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group
    ADD CONSTRAINT collection_group_pkey PRIMARY KEY (id);


--
-- Name: collection_group_user collection_group_user_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_user
    ADD CONSTRAINT collection_group_user_pkey PRIMARY KEY (id);


--
-- Name: collection_link collection_link_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_link
    ADD CONSTRAINT collection_link_pkey PRIMARY KEY (id);


--
-- Name: collection_user collection_user_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_user
    ADD CONSTRAINT collection_user_pkey PRIMARY KEY (id);


--
-- Name: collections_datasets collections_datasets_collection_id_dataset_id_508b2225_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections_datasets
    ADD CONSTRAINT collections_datasets_collection_id_dataset_id_508b2225_uniq UNIQUE (collection_id, dataset_id);


--
-- Name: collections_datasets collections_datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections_datasets
    ADD CONSTRAINT collections_datasets_pkey PRIMARY KEY (id);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: dataset_file dataset_file_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.dataset_file
    ADD CONSTRAINT dataset_file_pkey PRIMARY KEY (id);


--
-- Name: dataset_user dataset_user_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.dataset_user
    ADD CONSTRAINT dataset_user_pkey PRIMARY KEY (id);


--
-- Name: datasets datasets_label_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_label_key UNIQUE (label);


--
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_group_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_group_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_task_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: guardian_groupobjectpermission guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq UNIQUE (group_id, permission_id, object_pk);


--
-- Name: guardian_groupobjectpermission guardian_groupobjectpermission_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobjectpermission_pkey PRIMARY KEY (id);


--
-- Name: guardian_userobjectpermission guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq UNIQUE (user_id, permission_id, object_pk);


--
-- Name: guardian_userobjectpermission guardian_userobjectpermission_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermission_pkey PRIMARY KEY (id);


--
-- Name: hits hits_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.hits
    ADD CONSTRAINT hits_pkey PRIMARY KEY (id);


--
-- Name: links links_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_pkey PRIMARY KEY (id);


--
-- Name: log log_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_pkey PRIMARY KEY (id);


--
-- Name: place_depiction place_depiction_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_depiction
    ADD CONSTRAINT place_depiction_pkey PRIMARY KEY (id);


--
-- Name: place_description place_description_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_description
    ADD CONSTRAINT place_description_pkey PRIMARY KEY (id);


--
-- Name: place_geom place_geom_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_geom
    ADD CONSTRAINT place_geom_pkey PRIMARY KEY (id);


--
-- Name: place_link place_link_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_link
    ADD CONSTRAINT place_link_pkey PRIMARY KEY (id);


--
-- Name: place_name place_name_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_name
    ADD CONSTRAINT place_name_pkey PRIMARY KEY (id);


--
-- Name: place_related place_related_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_related
    ADD CONSTRAINT place_related_pkey PRIMARY KEY (id);


--
-- Name: place_type place_type_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_type
    ADD CONSTRAINT place_type_pkey PRIMARY KEY (id);


--
-- Name: place_when place_when_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_when
    ADD CONSTRAINT place_when_pkey PRIMARY KEY (id);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: resource_file resource_file_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resource_file
    ADD CONSTRAINT resource_file_pkey PRIMARY KEY (id);


--
-- Name: resource_image resource_image_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resource_image
    ADD CONSTRAINT resource_image_pkey PRIMARY KEY (id);


--
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: sources sources_src_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_src_id_key UNIQUE (src_id);


--
-- Name: trace_annotations trace_annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_annotations
    ADD CONSTRAINT trace_annotations_pkey PRIMARY KEY (id);


--
-- Name: trace_relations trace_relations_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_relations
    ADD CONSTRAINT trace_relations_pkey PRIMARY KEY (id);


--
-- Name: types types_aat_id_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_aat_id_key UNIQUE (aat_id);


--
-- Name: types types_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.types
    ADD CONSTRAINT types_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: areas_owner_id_c2311fbb; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX areas_owner_id_c2311fbb ON public.areas USING btree (owner_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: captcha_captchastore_hashkey_cbe8d15a_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX captcha_captchastore_hashkey_cbe8d15a_like ON public.captcha_captchastore USING btree (hashkey varchar_pattern_ops);


--
-- Name: collection_collplace_collection_id_e61872c8; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_collplace_collection_id_e61872c8 ON public.collection_collplace USING btree (collection_id);


--
-- Name: collection_collplace_place_id_5820ae35; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_collplace_place_id_5820ae35 ON public.collection_collplace USING btree (place_id);


--
-- Name: collection_group_collections_collection_id_e4df272f; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_group_collections_collection_id_e4df272f ON public.collection_group_collections USING btree (collection_id);


--
-- Name: collection_group_collections_collectiongroup_id_79ca8530; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_group_collections_collectiongroup_id_79ca8530 ON public.collection_group_collections USING btree (collectiongroup_id);


--
-- Name: collection_group_owner_id_bc10b69f; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_group_owner_id_bc10b69f ON public.collection_group USING btree (owner_id);


--
-- Name: collection_group_user_collectiongroup_id_33554608; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_group_user_collectiongroup_id_33554608 ON public.collection_group_user USING btree (collectiongroup_id);


--
-- Name: collection_group_user_user_id_52dd1787; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_group_user_user_id_52dd1787 ON public.collection_group_user USING btree (user_id);


--
-- Name: collection_link_collection_id_1829f134; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_link_collection_id_1829f134 ON public.collection_link USING btree (collection_id);


--
-- Name: collection_user_collection_id_b16dafdb; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_user_collection_id_b16dafdb ON public.collection_user USING btree (collection_id);


--
-- Name: collection_user_user_id_4f1f2a74; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collection_user_user_id_4f1f2a74 ON public.collection_user USING btree (user_id);


--
-- Name: collections_collection_collection_group_fc3cd539; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collections_collection_collection_group_fc3cd539 ON public.collections USING btree ("group");


--
-- Name: collections_datasets_collection_id_d2926e44; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collections_datasets_collection_id_d2926e44 ON public.collections_datasets USING btree (collection_id);


--
-- Name: collections_datasets_dataset_id_1485e6bc; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collections_datasets_dataset_id_1485e6bc ON public.collections_datasets USING btree (dataset_id);


--
-- Name: collections_owner_id_661190cb; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX collections_owner_id_661190cb ON public.collections USING btree (owner_id);


--
-- Name: comments_place_id_id_83ac017c; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX comments_place_id_id_83ac017c ON public.comments USING btree (place_id_id);


--
-- Name: comments_user_id_b8fd0b64; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX comments_user_id_b8fd0b64 ON public.comments USING btree (user_id);


--
-- Name: countries_mpoly_4b377c74_id; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX countries_mpoly_4b377c74_id ON public.countries USING gist (mpoly);


--
-- Name: dataset_file_dataset_id_id_a339f466; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX dataset_file_dataset_id_id_a339f466 ON public.dataset_file USING btree (dataset_id_id);


--
-- Name: dataset_user_dataset_id_id_c59abe05; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX dataset_user_dataset_id_id_c59abe05 ON public.dataset_user USING btree (dataset_id_id);


--
-- Name: dataset_user_user_id_id_8a28bbed; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX dataset_user_user_id_id_8a28bbed ON public.dataset_user USING btree (user_id_id);


--
-- Name: datasets_bbox_88f745dd_id; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX datasets_bbox_88f745dd_id ON public.datasets USING gist (bbox);


--
-- Name: datasets_id_5ec54b_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX datasets_id_5ec54b_idx ON public.datasets USING btree (id, label);


--
-- Name: datasets_label_154c4bc3_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX datasets_label_154c4bc3_like ON public.datasets USING btree (label varchar_pattern_ops);


--
-- Name: datasets_owner_id_f5e949cb; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX datasets_owner_id_f5e949cb ON public.datasets USING btree (owner_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cele_date_cr_bd6c1d_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_date_cr_bd6c1d_idx ON public.django_celery_results_groupresult USING btree (date_created);


--
-- Name: django_cele_date_cr_f04a50_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_date_cr_f04a50_idx ON public.django_celery_results_taskresult USING btree (date_created);


--
-- Name: django_cele_date_do_caae0e_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_date_do_caae0e_idx ON public.django_celery_results_groupresult USING btree (date_done);


--
-- Name: django_cele_date_do_f59aad_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_date_do_f59aad_idx ON public.django_celery_results_taskresult USING btree (date_done);


--
-- Name: django_cele_status_9b6201_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_status_9b6201_idx ON public.django_celery_results_taskresult USING btree (status);


--
-- Name: django_cele_task_na_08aec9_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_task_na_08aec9_idx ON public.django_celery_results_taskresult USING btree (task_name);


--
-- Name: django_cele_worker_d54dd8_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_cele_worker_d54dd8_idx ON public.django_celery_results_taskresult USING btree (worker);


--
-- Name: django_celery_results_chordcounter_group_id_1f70858c_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_celery_results_chordcounter_group_id_1f70858c_like ON public.django_celery_results_chordcounter USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_groupresult_group_id_a085f1a9_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_celery_results_groupresult_group_id_a085f1a9_like ON public.django_celery_results_groupresult USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_taskresult_task_id_de0d95bf_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_celery_results_taskresult_task_id_de0d95bf_like ON public.django_celery_results_taskresult USING btree (task_id varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: guardian_gr_content_ae6aec_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_gr_content_ae6aec_idx ON public.guardian_groupobjectpermission USING btree (content_type_id, object_pk);


--
-- Name: guardian_groupobjectpermission_content_type_id_7ade36b8; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_groupobjectpermission_content_type_id_7ade36b8 ON public.guardian_groupobjectpermission USING btree (content_type_id);


--
-- Name: guardian_groupobjectpermission_group_id_4bbbfb62; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_groupobjectpermission_group_id_4bbbfb62 ON public.guardian_groupobjectpermission USING btree (group_id);


--
-- Name: guardian_groupobjectpermission_permission_id_36572738; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_groupobjectpermission_permission_id_36572738 ON public.guardian_groupobjectpermission USING btree (permission_id);


--
-- Name: guardian_us_content_179ed2_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_us_content_179ed2_idx ON public.guardian_userobjectpermission USING btree (content_type_id, object_pk);


--
-- Name: guardian_userobjectpermission_content_type_id_2e892405; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_userobjectpermission_content_type_id_2e892405 ON public.guardian_userobjectpermission USING btree (content_type_id);


--
-- Name: guardian_userobjectpermission_permission_id_71807bfc; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_userobjectpermission_permission_id_71807bfc ON public.guardian_userobjectpermission USING btree (permission_id);


--
-- Name: guardian_userobjectpermission_user_id_d5c1e964; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX guardian_userobjectpermission_user_id_d5c1e964 ON public.guardian_userobjectpermission USING btree (user_id);


--
-- Name: hits_dataset_id_df3b455e; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX hits_dataset_id_df3b455e ON public.hits USING btree (dataset_id);


--
-- Name: hits_place_id_f313cda1; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX hits_place_id_f313cda1 ON public.hits USING btree (place_id);


--
-- Name: links_collection_group_id_8c1452d9; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX links_collection_group_id_8c1452d9 ON public.links USING btree (collection_group_id);


--
-- Name: links_collection_id_7cfa305f; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX links_collection_id_7cfa305f ON public.links USING btree (collection_id);


--
-- Name: links_place_id_5f8d543c; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX links_place_id_5f8d543c ON public.links USING btree (place_id);


--
-- Name: links_trace_annotation_id_1dec3dd5; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX links_trace_annotation_id_1dec3dd5 ON public.links USING btree (trace_annotation_id);


--
-- Name: log_dataset_id_a0578393; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX log_dataset_id_a0578393 ON public.log USING btree (dataset_id);


--
-- Name: log_user_id_18322c5d; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX log_user_id_18322c5d ON public.log USING btree (user_id);


--
-- Name: place_depiction_place_id_54f136b7; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_depiction_place_id_54f136b7 ON public.place_depiction USING btree (place_id);


--
-- Name: place_description_place_id_08574bb7; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_description_place_id_08574bb7 ON public.place_description USING btree (place_id);


--
-- Name: place_geom_geom_8caaca8f_id; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_geom_geom_8caaca8f_id ON public.place_geom USING gist (geom);


--
-- Name: place_geom_geom_src_569ea428; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_geom_geom_src_569ea428 ON public.place_geom USING btree (geom_src);


--
-- Name: place_geom_geom_src_569ea428_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_geom_geom_src_569ea428_like ON public.place_geom USING btree (geom_src varchar_pattern_ops);


--
-- Name: place_geom_place_id_7c3d81ea; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_geom_place_id_7c3d81ea ON public.place_geom USING btree (place_id);


--
-- Name: place_link_place_id_b45cce71; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_link_place_id_b45cce71 ON public.place_link USING btree (place_id);


--
-- Name: place_name_name_src_id_04626b79; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_name_name_src_id_04626b79 ON public.place_name USING btree (name_src_id);


--
-- Name: place_name_place_id_755c814c; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_name_place_id_755c814c ON public.place_name USING btree (place_id);


--
-- Name: place_related_place_id_7f026962; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_related_place_id_7f026962 ON public.place_related USING btree (place_id);


--
-- Name: place_type_place_id_badffa7b; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_type_place_id_badffa7b ON public.place_type USING btree (place_id);


--
-- Name: place_when_place_id_808ddc51; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX place_when_place_id_808ddc51 ON public.place_when USING btree (place_id);


--
-- Name: places_dataset_94dd498e; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX places_dataset_94dd498e ON public.places USING btree (dataset);


--
-- Name: places_dataset_94dd498e_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX places_dataset_94dd498e_like ON public.places USING btree (dataset varchar_pattern_ops);


--
-- Name: places_src_id_486bf2_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX places_src_id_486bf2_idx ON public.places USING btree (src_id, dataset);


--
-- Name: resource_file_resource_id_c1278ee6; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX resource_file_resource_id_c1278ee6 ON public.resource_file USING btree (resource_id);


--
-- Name: resource_image_resource_id_18fa37ea; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX resource_image_resource_id_18fa37ea ON public.resource_image USING btree (resource_id);


--
-- Name: resources_owner_id_e69b0ab7; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX resources_owner_id_e69b0ab7 ON public.resources USING btree (owner_id);


--
-- Name: sources_owner_id_826a31e1; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX sources_owner_id_826a31e1 ON public.sources USING btree (owner_id);


--
-- Name: sources_src_id_b9b478e7_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX sources_src_id_b9b478e7_like ON public.sources USING btree (src_id varchar_pattern_ops);


--
-- Name: trace_annot_collect_b0d79b_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_annot_collect_b0d79b_idx ON public.trace_annotations USING btree (collection);


--
-- Name: trace_annot_place_e86cee_idx; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_annot_place_e86cee_idx ON public.trace_annotations USING btree (place);


--
-- Name: trace_annotations_collection_7ccf0305; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_annotations_collection_7ccf0305 ON public.trace_annotations USING btree (collection);


--
-- Name: trace_annotations_owner_id_af52eb70; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_annotations_owner_id_af52eb70 ON public.trace_annotations USING btree (owner_id);


--
-- Name: trace_annotations_place_41de199a; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_annotations_place_41de199a ON public.trace_annotations USING btree (place);


--
-- Name: trace_relations_collection_caf4f9a6; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX trace_relations_collection_caf4f9a6 ON public.trace_relations USING btree (collection);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: karlg
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: areas areas_owner_id_c2311fbb_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_owner_id_c2311fbb_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_collplace collection_collplace_collection_id_e61872c8_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_collplace
    ADD CONSTRAINT collection_collplace_collection_id_e61872c8_fk_collections_id FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_collplace collection_collplace_place_id_5820ae35_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_collplace
    ADD CONSTRAINT collection_collplace_place_id_5820ae35_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_group_collections collection_group_col_collection_id_e4df272f_fk_collectio; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_collections
    ADD CONSTRAINT collection_group_col_collection_id_e4df272f_fk_collectio FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_group_collections collection_group_col_collectiongroup_id_79ca8530_fk_collectio; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_collections
    ADD CONSTRAINT collection_group_col_collectiongroup_id_79ca8530_fk_collectio FOREIGN KEY (collectiongroup_id) REFERENCES public.collection_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_group collection_group_owner_id_bc10b69f_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group
    ADD CONSTRAINT collection_group_owner_id_bc10b69f_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_group_user collection_group_use_collectiongroup_id_33554608_fk_collectio; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_user
    ADD CONSTRAINT collection_group_use_collectiongroup_id_33554608_fk_collectio FOREIGN KEY (collectiongroup_id) REFERENCES public.collection_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_group_user collection_group_user_user_id_52dd1787_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_group_user
    ADD CONSTRAINT collection_group_user_user_id_52dd1787_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_link collection_link_collection_id_1829f134_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_link
    ADD CONSTRAINT collection_link_collection_id_1829f134_fk_collections_id FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_user collection_user_collection_id_b16dafdb_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_user
    ADD CONSTRAINT collection_user_collection_id_b16dafdb_fk_collections_id FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collection_user collection_user_user_id_4f1f2a74_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collection_user
    ADD CONSTRAINT collection_user_user_id_4f1f2a74_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collections_datasets collections_datasets_collection_id_d2926e44_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections_datasets
    ADD CONSTRAINT collections_datasets_collection_id_d2926e44_fk_collections_id FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collections_datasets collections_datasets_dataset_id_1485e6bc_fk_datasets_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections_datasets
    ADD CONSTRAINT collections_datasets_dataset_id_1485e6bc_fk_datasets_id FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collections collections_group_154badb4_fk_collection_group_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_group_154badb4_fk_collection_group_id FOREIGN KEY ("group") REFERENCES public.collection_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: collections collections_owner_id_661190cb_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_owner_id_661190cb_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comments comments_place_id_id_83ac017c_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_place_id_id_83ac017c_fk_places_id FOREIGN KEY (place_id_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comments comments_user_id_b8fd0b64_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_b8fd0b64_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dataset_file dataset_file_dataset_id_id_a339f466_fk_datasets_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.dataset_file
    ADD CONSTRAINT dataset_file_dataset_id_id_a339f466_fk_datasets_id FOREIGN KEY (dataset_id_id) REFERENCES public.datasets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dataset_user dataset_user_dataset_id_id_c59abe05_fk_datasets_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.dataset_user
    ADD CONSTRAINT dataset_user_dataset_id_id_c59abe05_fk_datasets_id FOREIGN KEY (dataset_id_id) REFERENCES public.datasets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dataset_user dataset_user_user_id_id_8a28bbed_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.dataset_user
    ADD CONSTRAINT dataset_user_user_id_id_8a28bbed_fk_users_user_id FOREIGN KEY (user_id_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: datasets datasets_owner_id_f5e949cb_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_owner_id_f5e949cb_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_content_type_id_7ade36b8_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_content_type_id_7ade36b8_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_group_id_4bbbfb62_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_group_id_4bbbfb62_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_groupobjectpermission guardian_groupobject_permission_id_36572738_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_groupobjectpermission
    ADD CONSTRAINT guardian_groupobject_permission_id_36572738_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectp_content_type_id_2e892405_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectp_content_type_id_2e892405_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectp_permission_id_71807bfc_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectp_permission_id_71807bfc_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: guardian_userobjectpermission guardian_userobjectpermission_user_id_d5c1e964_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.guardian_userobjectpermission
    ADD CONSTRAINT guardian_userobjectpermission_user_id_d5c1e964_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: hits hits_dataset_id_df3b455e_fk_datasets_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.hits
    ADD CONSTRAINT hits_dataset_id_df3b455e_fk_datasets_id FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: hits hits_place_id_f313cda1_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.hits
    ADD CONSTRAINT hits_place_id_f313cda1_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: links links_collection_group_id_8c1452d9_fk_collection_group_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_collection_group_id_8c1452d9_fk_collection_group_id FOREIGN KEY (collection_group_id) REFERENCES public.collection_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: links links_collection_id_7cfa305f_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_collection_id_7cfa305f_fk_collections_id FOREIGN KEY (collection_id) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: links links_place_id_5f8d543c_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_place_id_5f8d543c_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: links links_trace_annotation_id_1dec3dd5_fk_trace_annotations_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.links
    ADD CONSTRAINT links_trace_annotation_id_1dec3dd5_fk_trace_annotations_id FOREIGN KEY (trace_annotation_id) REFERENCES public.trace_annotations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: log log_dataset_id_a0578393_fk_datasets_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_dataset_id_a0578393_fk_datasets_id FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: log log_user_id_18322c5d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.log
    ADD CONSTRAINT log_user_id_18322c5d_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_depiction place_depiction_place_id_54f136b7_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_depiction
    ADD CONSTRAINT place_depiction_place_id_54f136b7_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_description place_description_place_id_08574bb7_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_description
    ADD CONSTRAINT place_description_place_id_08574bb7_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_geom place_geom_geom_src_569ea428_fk_sources_src_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_geom
    ADD CONSTRAINT place_geom_geom_src_569ea428_fk_sources_src_id FOREIGN KEY (geom_src) REFERENCES public.sources(src_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_geom place_geom_place_id_7c3d81ea_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_geom
    ADD CONSTRAINT place_geom_place_id_7c3d81ea_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_link place_link_place_id_b45cce71_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_link
    ADD CONSTRAINT place_link_place_id_b45cce71_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_name place_name_name_src_id_04626b79_fk_sources_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_name
    ADD CONSTRAINT place_name_name_src_id_04626b79_fk_sources_id FOREIGN KEY (name_src_id) REFERENCES public.sources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_name place_name_place_id_755c814c_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_name
    ADD CONSTRAINT place_name_place_id_755c814c_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_related place_related_place_id_7f026962_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_related
    ADD CONSTRAINT place_related_place_id_7f026962_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_type place_type_place_id_badffa7b_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_type
    ADD CONSTRAINT place_type_place_id_badffa7b_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: place_when place_when_place_id_808ddc51_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.place_when
    ADD CONSTRAINT place_when_place_id_808ddc51_fk_places_id FOREIGN KEY (place_id) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: places places_dataset_94dd498e_fk_datasets_label; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_dataset_94dd498e_fk_datasets_label FOREIGN KEY (dataset) REFERENCES public.datasets(label) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resource_file resource_file_resource_id_c1278ee6_fk_resources_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resource_file
    ADD CONSTRAINT resource_file_resource_id_c1278ee6_fk_resources_id FOREIGN KEY (resource_id) REFERENCES public.resources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resource_image resource_image_resource_id_18fa37ea_fk_resources_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resource_image
    ADD CONSTRAINT resource_image_resource_id_18fa37ea_fk_resources_id FOREIGN KEY (resource_id) REFERENCES public.resources(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: resources resources_owner_id_e69b0ab7_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_owner_id_e69b0ab7_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sources sources_owner_id_826a31e1_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_owner_id_826a31e1_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trace_annotations trace_annotations_collection_7ccf0305_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_annotations
    ADD CONSTRAINT trace_annotations_collection_7ccf0305_fk_collections_id FOREIGN KEY (collection) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trace_annotations trace_annotations_owner_id_af52eb70_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_annotations
    ADD CONSTRAINT trace_annotations_owner_id_af52eb70_fk_users_user_id FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trace_annotations trace_annotations_place_41de199a_fk_places_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_annotations
    ADD CONSTRAINT trace_annotations_place_41de199a_fk_places_id FOREIGN KEY (place) REFERENCES public.places(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trace_relations trace_relations_collection_caf4f9a6_fk_collections_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.trace_relations
    ADD CONSTRAINT trace_relations_collection_caf4f9a6_fk_collections_id FOREIGN KEY (collection) REFERENCES public.collections(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: karlg
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

