# Generated by Django 4.1.7 on 2026-08-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'action item', 'verbose_name_plural': 'action items'},
        ),
        migrations.AlterModelOptions(
            name='actionitemstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'action-item status', 'verbose_name_plural': 'action-item statuses'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactrole',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'contact role', 'verbose_name_plural': 'contact roles'},
        ),
        migrations.AlterModelOptions(
            name='contactstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'contact status', 'verbose_name_plural': 'contact statuses'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-planned_for', 'title'], 'verbose_name': 'content item', 'verbose_name_plural': 'content items'},
        ),
        migrations.AlterModelOptions(
            name='contentitemtype',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'content type', 'verbose_name_plural': 'content types'},
        ),
        migrations.AlterModelOptions(
            name='contentstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'content status', 'verbose_name_plural': 'content statuses'},
        ),
        migrations.AlterModelOptions(
            name='digitizationstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'digitization status', 'verbose_name_plural': 'digitization statuses'},
        ),
        migrations.AlterModelOptions(
            name='discoverysource',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'discovery source', 'verbose_name_plural': 'discovery sources'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'ordering': ['-opened_on'], 'verbose_name': 'engagement', 'verbose_name_plural': 'engagements'},
        ),
        migrations.AlterModelOptions(
            name='engagementoutcome',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'engagement outcome', 'verbose_name_plural': 'engagement outcomes'},
        ),
        migrations.AlterModelOptions(
            name='engagementstage',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'conversation stage', 'verbose_name_plural': 'conversation stages'},
        ),
        migrations.AlterModelOptions(
            name='intakestatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'intake status', 'verbose_name_plural': 'intake statuses'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-occurred_on', '-created_at'], 'verbose_name': 'interaction', 'verbose_name_plural': 'interactions'},
        ),
        migrations.AlterModelOptions(
            name='interactionchannel',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'interaction channel', 'verbose_name_plural': 'interaction channels'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name'], 'verbose_name': 'organisation', 'verbose_name_plural': 'organisations'},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'organisation type', 'verbose_name_plural': 'organisation types'},
        ),
        migrations.AlterModelOptions(
            name='permissionstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'permission status', 'verbose_name_plural': 'permission statuses'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'priority', 'verbose_name_plural': 'priorities'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'project status', 'verbose_name_plural': 'project statuses'},
        ),
        migrations.AlterModelOptions(
            name='reviewrecommendation',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'review recommendation', 'verbose_name_plural': 'review recommendations'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title'], 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.AlterModelOptions(
            name='sourcesuggestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'source suggestion', 'verbose_name_plural': 'source suggestions'},
        ),
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'source type', 'verbose_name_plural': 'source types'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'editorial stage', 'verbose_name_plural': 'editorial stages'},
        ),
        migrations.AlterModelOptions(
            name='trackedgazetteer',
            options={'ordering': ['title'], 'verbose_name': 'gazetteer', 'verbose_name_plural': 'gazetteers'},
        ),
    ]
