# Generated by Django 4.1.7 on 2026-09-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grace', '0003_dataset_and_person_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='personrole',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'person role', 'verbose_name_plural': 'person roles'},
        ),
        migrations.AlterModelOptions(
            name='personstatus',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'person status', 'verbose_name_plural': 'person statuses'},
        ),
        migrations.AlterModelOptions(
            name='trackeddataset',
            options={'ordering': ['title'], 'verbose_name': 'dataset', 'verbose_name_plural': 'datasets'},
        ),
        migrations.AlterField(
            model_name='engagement',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='grace.trackeddataset', verbose_name='dataset'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text="Leave blank to inherit the dataset's responsible person. Set only to deliberately override it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='person',
            field=models.ForeignKey(help_text="Normally the engagement's person; set explicitly so the log can be queried per person without a join.", on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='grace.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='discovery_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='grace.discoverysource'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='grace.organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='grace_people', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='grace.personrole'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='grace.personstatus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to a WHG account, if this person has one. When set, email, ORCID and affiliation are read from the account and the local copies here are cleared.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='discovery_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='grace.discoverysource'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Who can actually grant permission to publish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='grace.organisation'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The one accountable owner. Engagements inherit this unless they deliberately override it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_datasets', to=settings.AUTH_USER_MODEL, verbose_name='responsible person'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='grace.person'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='permission_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='grace.permissionstatus'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='grace.project'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='UN M49. Several is fine and normal.', related_name='grace_datasets', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Editorial stage only. Published / indexed are read from the Register, not set here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='grace.stage'),
        ),
    ]
