# Generated by Django 4.1.7 on 2026-09-02 08:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_seed_authority_licences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_gazetteerregistryentry_embargo_release_at_and_more'),
        ('grace', '0004_alter_person_options_alter_personrole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Stable machine key. Set automatically from the label; safe to leave blank. Changing it may break imports.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional note on when to use this term.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first in pick-lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a term without deleting it. Retired terms stay attached to existing records but are hidden from new pick-lists.')),
            ],
            options={
                'verbose_name': 'data format',
                'verbose_name_plural': 'data formats',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Stable machine key. Set automatically from the label; safe to leave blank. Changing it may break imports.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional note on when to use this term.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first in pick-lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a term without deleting it. Retired terms stay attached to existing records but are hidden from new pick-lists.')),
                ('is_undeliverable', models.BooleanField(default=False, help_text="Tick for states meaning 'do not send to this address' — bounced, unsubscribed. Used to keep dead addresses out of any list we hand to the mailing platform.")),
            ],
            options={
                'verbose_name': 'email status',
                'verbose_name_plural': 'email statuses',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeometryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Stable machine key. Set automatically from the label; safe to leave blank. Changing it may break imports.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional note on when to use this term.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first in pick-lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a term without deleting it. Retired terms stay attached to existing records but are hidden from new pick-lists.')),
            ],
            options={
                'verbose_name': 'geometry',
                'verbose_name_plural': 'geometry statuses',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Stable machine key. Set automatically from the label; safe to leave blank. Changing it may break imports.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional note on when to use this term.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers appear first in pick-lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a term without deleting it. Retired terms stay attached to existing records but are hidden from new pick-lists.')),
            ],
            options={
                'verbose_name': 'review type',
                'verbose_name_plural': 'review types',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='email_status_checked_on',
            field=models.DateField(blank=True, null=True, verbose_name='address last checked'),
        ),
        migrations.AddField(
            model_name='source',
            name='people',
            field=models.ManyToManyField(blank=True, help_text="Authors, compilers and editors we hold a record for. ‘Author / compiler’ above stays as the bibliography writes it; this is the queryable version, and it is what lets a person's own page show the sources they are behind.", related_name='sources', to='grace.person'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='expected_licence',
            field=models.ForeignKey(blank=True, help_text="The licence under discussion — not a copy of the Register's. Leave blank until someone has actually said.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grace_expected_datasets', to='licensing.license', verbose_name='licence (offered)'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='expected_record_count',
            field=models.IntegerField(blank=True, help_text="Roughly how many places we have been told to expect. Once accessioned, the Register's own count supersedes this.", null=True, verbose_name='records (expected)'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='expected_rights_holder',
            field=models.CharField(blank=True, max_length=255, verbose_name='rights holder (as told)'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='reconciled_against',
            field=models.ManyToManyField(blank=True, help_text='Authorities this data has been matched to. Drawn from the Gazetteer Register rather than typed, so it is the same list of authorities the rest of WHG uses.', related_name='grace_reconciliation_targets', to='api.gazetteerregistryentry', verbose_name='reconciled against'),
        ),
        migrations.AlterField(
            model_name='source',
            name='derived_datasets',
            field=models.ManyToManyField(blank=True, help_text='Datasets extracted FROM this source. This is the provenance chain — keep it accurate.', related_name='derived_from_sources', to='grace.trackeddataset'),
        ),
        migrations.AlterField(
            model_name='source',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Datasets this source describes.', related_name='documented_by', to='grace.trackeddataset'),
        ),
        migrations.AlterField(
            model_name='trackeddataset',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, help_text='ISO 639-3 codes, comma-separated — e.g. <code>eng, fra, ara</code>. The data is multilingual; free text will not group.', size=None),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateField(blank=True, null=True, verbose_name='sent to reviewer')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='returned')),
                ('comments', models.TextField(blank=True)),
                ('shared_with_author_on', models.DateField(blank=True, help_text='Until this is filled in, nothing has happened as far as the contributor can tell.', null=True, verbose_name='shared with author')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grace.trackeddataset')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='grace.reviewrecommendation')),
                ('review_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='grace.reviewtype', verbose_name='type')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Anyone in the People register — a colleague or an outside reviewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='grace.person')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-sent_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='email_status',
            field=models.ForeignKey(blank=True, help_text='Whether the address still works. GRACE is not the mailing list — the sending platform owns subscriptions — but a bounce recorded here stops us losing the person along with their address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='grace.emailstatus'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='data_format',
            field=models.ForeignKey(blank=True, help_text="How the data arrives. A Linked Places file is a day's work; a set of page scans is a project.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='grace.dataformat'),
        ),
        migrations.AddField(
            model_name='trackeddataset',
            name='geometry_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='grace.geometrystatus', verbose_name='coordinates'),
        ),
    ]
