# Use the PostGIS Docker image
FROM postgis/postgis:15-3.4

# Install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    lsb-release

# Install WAL-G (Used in docker-compose-prod.yml only)
RUN wget https://github.com/wal-g/wal-g/releases/download/v3.0.2/wal-g-pg-ubuntu-20.04-amd64.tar.gz \
    && tar -zxvf wal-g-pg-ubuntu-20.04-amd64.tar.gz \
    && mv wal-g-pg-ubuntu-20.04-amd64 /usr/local/bin/wal-g \
    && rm wal-g-pg-ubuntu-20.04-amd64.tar.gz

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy Google Cloud Services authentication file to container
RUN mkdir -p /etc/wal-g
COPY ./credentials/whg-backup-430708-e33f94999eab.json /etc/wal-g/gcs-credentials.json
RUN chown postgres:postgres /etc/wal-g/gcs-credentials.json

# Set up the entrypoint script
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./start-postgres.sh /docker-entrypoint-initdb.d/10_postgis.sh
RUN sed -i 's/\r$//g' /docker-entrypoint-initdb.d/10_postgis.sh
RUN chmod +x /docker-entrypoint-initdb.d/10_postgis.sh
